---

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2.2
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'bin/*'
    - '*.gemspec'

# Disable metrics for now
Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

# Disable other remaining
Lint/ShadowedException:
  Enabled: false

# Allow model names with numbers
Naming/VariableNumber:
  Enabled: false

# Disable line length for now
Layout/LineLength:
  Enabled: false

# Allow both string styles
Style/StringLiterals:
  EnforcedStyle: single_quotes

# Allow both hash styles
Style/HashSyntax:
  EnforcedStyle: ruby19

# Documentation
Style/Documentation:
  Enabled: false
