name: Dependencies

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  # Update Ruby gem dependencies weekly
  update:
    name: Update
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

       - name: Set up Ruby
         uses: ruby/setup-ruby@v1
         with:
           ruby-version: '3.3'
           bundler-cache: true

      - name: Update Bundler
        run: gem update bundler

      - name: Update dependencies
        run: |
          bundle update --conservative
          bundle clean

      - name: Run tests
        run: |
          bundle install
          bundle exec ruby tests/runner.rb

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'chore: update dependencies'
          body: |
            ## Dependency Updates
            
            This PR updates gem dependencies to their latest compatible versions.
            
            ### Changes
            - Updated gems via `bundle update --conservative`
            - Ran test suite to ensure compatibility
            
            ### Testing
            - [x] All tests pass
            - [x] Dependencies are compatible
            
            Auto-generated by GitHub Actions.
          branch: chore/update-dependencies
          delete-branch: true