name: Gemini CLI Integration

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  run-gemini-cli:
    name: Run Gemini CLI
    runs-on: ubuntu-latest
    steps:
    - name: Run Gemini CLI
      uses: google-github-actions/run-gemini-cli@v0.1.12
      with:
        command: version
        gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
