name: Gemini CLI Integration

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  run-gemini-cli:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Gemini CLI
      uses: google-github-actions/run-gemini-cli@v0.1.12
      with:
        # Add your Gemini CLI command here
        command: version
        # Uncomment and set your API key if needed
        # api_key: ${{ secrets.GEMINI_API_KEY }}
