name: Gemini CLI Integration

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  run-gemini-cli:
    name: Run Gemini CLI
    runs-on: ubuntu-latest
    steps:
    - name: Install Gemini CLI
      run: npm install -g @google/gemini-cli@latest
      
    - name: Check Gemini CLI version
      run: gemini --version
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
